name: "Test"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  pull_request_target:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      # These steps require access to secrets, so they can't run on non-reviewed pull requests.
      - name: "Secrets"
        run: echo ${{ secrets.MY_SUPER_SECRET_STRING }}
        if: ${{ github.event != 'pull_request' }}
      - name: "Show Commit"
        run: git rev-parse HEAD
